# Generated by Django 2.0.5 on 2020-04-04 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0002_projects'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='person',
            table='tb_person',
        ),
        migrations.AlterModelTable(
            name='projects',
            table='tb_projects',
        ),
    ]
