# Generated by Django 2.0.5 on 2020-04-04 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0003_auto_20200405_0039'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projects',
            options={'verbose_name': '项目', 'verbose_name_plural': '项目'},
        ),
    ]
