# Generated by Django 2.0.5 on 2020-04-04 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0004_auto_20200405_0043'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'verbose_name': '用户', 'verbose_name_plural': '用户'},
        ),
    ]
