# Generated by Django 2.0.5 on 2020-04-04 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0005_auto_20200405_0111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='first_name',
            field=models.CharField(help_text='姓', max_length=30, verbose_name='姓'),
        ),
        migrations.AlterField(
            model_name='person',
            name='last_name',
            field=models.CharField(help_text='名字', max_length=30, verbose_name='名字'),
        ),
    ]
